apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: picsou-db
  namespace: picsou-finance
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: picsou
      owner: picsou
      secret:
        name: picsou-db-credentials
  storage:
    size: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
