apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: picsou-app-secrets
  namespace: picsou
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: picsou-app-secrets
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: secret/data/picsou/app
        property: jwt_secret
    - secretKey: crypto-encryption-key
      remoteRef:
        key: secret/data/picsou/app
        property: crypto_encryption_key
