apiVersion: apps/v1
kind: Deployment
metadata:
  name: picsou-tr-auth
  namespace: picsou
  labels:
    app.kubernetes.io/name: picsou-tr-auth
    app.kubernetes.io/component: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: picsou-tr-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: picsou-tr-auth
        app.kubernetes.io/component: sidecar
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: tr-auth
          image: ghcr.io/zoeille/picsou-finance/tr-auth:1.0.14
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          ports:
            - name: http
              containerPort: 8001
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
