-- Extend account_type enum with real estate and loan types
ALTER TYPE account_type ADD VALUE 'REAL_ESTATE' BEFORE 'OTHER';
ALTER TYPE account_type ADD VALUE 'LOAN' BEFORE 'OTHER';

-- Real estate property metadata (1:1 with account)
CREATE TABLE real_estate_metadata (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT          NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    purchase_price  NUMERIC(20, 8)  NOT NULL,
    purchase_date   DATE,
    surface_area    NUMERIC(10, 2),
    address         VARCHAR(500),
    property_type   VARCHAR(50),
    rental_income   NUMERIC(20, 8)  DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_real_estate_metadata_account UNIQUE (account_id)
);

-- Debt / loan metadata (1:1 with account)
CREATE TABLE debt (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          BIGINT          NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    linked_account_id   BIGINT          REFERENCES account(id) ON DELETE SET NULL,
    borrowed_amount     NUMERIC(20, 8)  NOT NULL,
    interest_rate       NUMERIC(5, 4),
    monthly_payment     NUMERIC(20, 8),
    lender_name         VARCHAR(100),
    start_date          DATE,
    end_date            DATE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_debt_account UNIQUE (account_id)
);

CREATE INDEX idx_debt_linked_account ON debt(linked_account_id)
    WHERE linked_account_id IS NOT NULL;
