package com.picsou.port;

public enum GroupamaEsErrorCode {
    INVALID_CREDENTIALS,
    INVALID_OTP,
    AUTH_ATTEMPT_EXPIRED,
    SESSION_EXPIRED,
    ACTION_REQUIRED,
    PORTFOLIO_INCOMPLETE,
    UPSTREAM_FORMAT_CHANGED,
    UPSTREAM_UNAVAILABLE,
    INVALID_DATA,
    INTERNAL_ERROR
}
